from aiogram.fsm.state import State, StatesGroup


class AdminStates(StatesGroup):
    menu = State()
    users_search = State()
    srs_confirm = State()
    content_user = State()
    content_page = State()
    content_edit = State()
    credits_add_id = State()
    credits_add_seconds = State()
    credits_forward_wait = State()
    credits_forward_seconds = State()
    package_select = State()
    package_edit = State()
    package_seconds = State()
    package_manual_price = State()
    package_stars_price = State()
    admin_contact_username = State()
    admins_menu = State()
    admins_add_method = State()
    admins_add_id = State()
    admins_add_forward = State()
    basic_limit_edit = State()
    full_test_charge_edit = State()
    test_limits_edit = State()
    level_test_menu = State()
    level_test_json_input = State()
    level_test_manual_level_tag = State()
    level_test_manual_difficulty = State()
    level_test_manual_type = State()
    level_test_manual_prompt = State()
    level_test_manual_choices = State()
    level_test_manual_correct_answer = State()
    level_test_manual_accepted_answers = State()
    level_test_manual_explanation = State()
    level_test_manual_is_active = State()
